#!/usr/bin/env bash
#
# uninstall-factory-linux.sh
#
# Remove a Factory desktop installation created by install-factory-linux.sh,
# including the launcher, XDG desktop entry, icons, and (optionally) the
# build cache and globally installed @factory/cli npm package.
#
# Usage:
#   ./uninstall-factory-linux.sh
#   PREFIX=/opt/Factory sudo -E ./uninstall-factory-linux.sh
#   REMOVE_CACHE=1 ./uninstall-factory-linux.sh
#   REMOVE_GLOBAL_CLI=1 ./uninstall-factory-linux.sh
#
set -euo pipefail

# ---------------------------------------------------------------------------
# Config (mirrors install-factory-linux.sh defaults)
# ---------------------------------------------------------------------------
: "${PREFIX:=${HOME}/.local/share}"
PREFIX="$(readlink -f "$PREFIX")"
APP_DIR="${PREFIX}/Factory"
: "${BIN_DIR:=${HOME}/.local/bin}"
BIN_DIR="$(readlink -f "$BIN_DIR")"
CACHE_DIR="${HOME}/.cache/factory-linux"

# Remove ~/.cache/factory-linux build artifacts?
: "${REMOVE_CACHE:=0}"

# Also run `npm uninstall -g @factory/cli` if installed?
: "${REMOVE_GLOBAL_CLI:=0}"

# Logging
log()  { printf '\033[1;34m[factory]\033[0m %s\n' "$*" >&2; }
warn() { printf '\033[1;33m[factory]\033[0m %s\n' "$*" >&2; }
err()  { printf '\033[1;31m[factory]\033[0m %s\n' "$*" >&2; }
die()  { err "$*"; exit 1; }

is_our_launcher() { # path
  local f="$1"
  [[ -f "$f" ]] && grep -q 'Auto-generated by install-factory-linux.sh' "$f"
}

remove_if_ours() { # path description
  local path="$1" desc="$2"
  if [[ ! -e "$path" ]]; then
    return 0
  fi
  if is_our_launcher "$path"; then
    rm -f "$path"
    log "Removed $desc: $path"
  else
    warn "Skipped $desc (not created by install-factory-linux.sh): $path"
  fi
}

remove_app_dir() {
  if [[ ! -d "$APP_DIR" ]]; then
    log "App directory not found: $APP_DIR"
    return 0
  fi
  rm -rf "$APP_DIR"
  log "Removed app directory: $APP_DIR"
}

remove_factory_launcher() {
  remove_if_ours "$BIN_DIR/factory" "launcher"
}

remove_desktop_entry() {
  local apps="${XDG_DATA_HOME:-$HOME/.local/share}/applications"
  local desktop="$apps/factory.desktop"
  if [[ ! -f "$desktop" ]]; then
    log "Desktop entry not found: $desktop"
    return 0
  fi
  if grep -q 'install-factory-linux.sh\|Factory Droids (Linux port)' "$desktop" 2>/dev/null \
     || grep -q "Exec=$BIN_DIR/factory" "$desktop" 2>/dev/null; then
    rm -f "$desktop"
    log "Removed desktop entry: $desktop"
    update-desktop-database "$apps" 2>/dev/null || true
  else
    warn "Skipped desktop entry (does not look like ours): $desktop"
  fi
}

remove_icons() {
  local icons="${XDG_DATA_HOME:-$HOME/.local/share}/icons/hicolor"
  local removed=0
  local dir
  for dir in "$icons"/*/apps; do
    [[ -d "$dir" ]] || continue
    if [[ -f "$dir/factory.png" ]]; then
      rm -f "$dir/factory.png"
      removed=1
      # Drop empty apps/ and size dirs left behind.
      rmdir "$dir" 2>/dev/null || true
      rmdir "${dir%/apps}" 2>/dev/null || true
    fi
  done
  if [[ "$removed" == "1" ]]; then
    log "Removed Factory icons under $icons"
    gtk-update-icon-cache -f -t "${icons%/hicolor}" 2>/dev/null || true
  else
    log "No Factory icons found under $icons"
  fi
}

remove_cache() {
  if [[ "$REMOVE_CACHE" != "1" ]]; then
    warn "Cache kept at $CACHE_DIR (set REMOVE_CACHE=1 to delete)."
    return 0
  fi
  if [[ ! -d "$CACHE_DIR" ]]; then
    log "Cache directory not found: $CACHE_DIR"
    return 0
  fi
  rm -rf "$CACHE_DIR"
  log "Removed cache: $CACHE_DIR"
}

remove_global_cli() {
  if [[ "$REMOVE_GLOBAL_CLI" != "1" ]]; then
    return 0
  fi
  if ! command -v npm >/dev/null 2>&1; then
    warn "npm not found; skipping global @factory/cli removal"
    return 0
  fi
  if npm list -g @factory/cli --depth=0 >/dev/null 2>&1; then
    log "Removing global npm package @factory/cli"
    npm uninstall -g @factory/cli
  else
    log "Global @factory/cli is not installed"
  fi
}

warn_if_running() {
  if pgrep -x electron >/dev/null 2>&1 && pgrep -f 'Factory|factory\.desktop|app\.asar' >/dev/null 2>&1; then
    warn "Factory may still be running. Quit the app before uninstalling."
  fi
}

main() {
  log "Uninstalling Factory desktop (prefix=$PREFIX, bin=$BIN_DIR)"
  warn_if_running
  remove_factory_launcher
  remove_desktop_entry
  remove_icons
  remove_app_dir
  remove_cache
  remove_global_cli
  echo
  log "Done."
}

main "$@"
